{"name": "test_func2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 != 1", "trace": "@pytest.mark.unfinished\n    def test_func2():\n>       assert 1 != 1\nE       assert 1 != 1\n\ncases\\test_标记.py:17: AssertionError"}, "start": 1600663696025, "stop": 1600663696025, "uuid": "33b6f4c7-aeb1-4239-b557-64adc485ea96", "historyId": "cfec532c61c8e9d6c0921a806a297421", "testCaseId": "ffb63986f70c421d49fec13c37aee2d0", "fullName": "cases.test_标记#test_func2", "labels": [{"name": "tag", "value": "unfinished"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_标记"}, {"name": "host", "value": "DESKTOP-K0CIH3F"}, {"name": "thread", "value": "2736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_标记"}]}