{"name": "test_func3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 != 1", "trace": "@pytest.mark.wait\n    def test_func3():\n>       assert 1 != 1\nE       assert 1 != 1\n\ncases\\test_标记.py:22: AssertionError"}, "start": 1600663696076, "stop": 1600663696076, "uuid": "e9a3729c-959c-48b2-96e6-5f2ae8181058", "historyId": "3910f7101993e1661ad7b8dac80cd720", "testCaseId": "de3c55de5749b701fe38399a3281b1f8", "fullName": "cases.test_标记#test_func3", "labels": [{"name": "tag", "value": "wait"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_标记"}, {"name": "host", "value": "DESKTOP-K0CIH3F"}, {"name": "thread", "value": "2736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_标记"}]}